function f = carico2(x,y)
%CARICO2
%    F = CARICO2(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    07-Feb-2017 01:29:05

t3 = y.^2;
t2 = t3-1.0;
t4 = t2.^2;
t5 = x.^2;
t6 = t5-1.0;
f = t4.*t5.*5.0e5+t4.*t6.*2.5e5+t4.*x.*(3.0./2.0)+t2.*t6.*x+t3.*t6.*x.*2.0+t2.*t6.*x.*y.*1.0e6;
