function f = carico1(x,y)
%CARICO1
%    F = CARICO1(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    07-Feb-2017 01:29:05

t3 = x.^2;
t2 = t3-1.0;
t4 = t2.^2;
t5 = y.^2;
t6 = t5-1.0;
f = t4.*t5.*-5.0e5-t4.*t6.*2.5e5-t4.*y.*(3.0./2.0)-t2.*t6.*y-t3.*t6.*y.*2.0-t2.*t6.*x.*y.*1.0e6;
